global using BuildingBlocks.Core.CQRS;
global using Catalog.API.Models;
global using Carter;
global using Mapster;
global using MediatR;
global using Marten;
global using FluentValidation;
global using BuildingBlocks.Core.Behaviors;
global using BuildingBlocks.Core.Exceptions.Handler;